version: '2'
networks:
  default:
    external:
      name: kafka_net
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "10083:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "10082:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.254.28
      KAFKA_ADVERTISED_PORT: 10082
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  monitor:
    image: zhaomoran/kafkaoffsetmonitor
    ports:
      - "10084:8080"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      REFRESH_TIME: "10.seconds"
      RETAIN_TIME: "2.days"
